export * from '@/components/ClassPlaceSlides/ClassPlaceSlide1'
export * from '@/components/ClassPlaceSlides/ClassPlaceSlide2'
export * from '@/components/ClassPlaceSlides/ClassPlaceSlide3'
export * from '@/components/ClassPlaceSlides/ClassPlaceSlideOtona'
export * from '@/components/ClassPlaceSlides/ClassPlaceSlideKodomo'
export * from '@/components/ClassPlaceSlides/ClassPlaceSlideDenshi'
